apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: moremoremusic-msa
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: broker
    app.kubernetes.io/part-of: moremoremusic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc-backup
  namespace: moremoremusic-msa
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: moremoremusic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard